before:
  hooks:
    - go mod download
    # - go generate ./...
builds:
  - main: ./cmd/gemserve
    binary: gemserve
    goarch:
      - amd64
      - 386
    goos:
      - darwin
      - linux
      - windows
    env:
      - CGO_ENABLED=0
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
